#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- $hubble := get .Values "hubble" | default dict }}
{{- if and (get $hubble "enabled" | default false) .Values.hubble.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hugegraph.hubble.name" . }}
  labels:
    {{- include "hugegraph.labels" . | nindent 4 }}
    app.kubernetes.io/component: hubble
  {{- with (get .Values.hubble.ingress "annotations") }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.hubble.ingress.className }}
  ingressClassName: {{ .Values.hubble.ingress.className | quote }}
  {{- end }}
  {{- with .Values.hubble.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.hubble.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "hugegraph.hubble.name" $ }}
                port:
                  number: {{ $.Values.hubble.port }}
          {{- end }}
    {{- end }}
{{- end }}
